idf_component_register(SRCS "power.c"
                    INCLUDE_DIRS "include"
                    REQUIRES "gpio_wrapper"
                    REQUIRES "logger"
                    REQUIRES "sm"
                    REQUIRES "task"
                    REQUIRES "esp_adc"
                    REQUIRES "cext"
                    REQUIRES "delay")