idf_component_register(SRCS "hygrometer.c"
                    INCLUDE_DIRS "include"
                    REQUIRES "logger"
                    REQUIRES "task"
                    REQUIRES "gpio_wrapper"
                    REQUIRES "adc_wrapper"
                    REQUIRES "cext"
                    REQUIRES "delay"
                    REQUIRES "esp_driver_ledc")
