#ifndef __SOL_GPIO_H__
#define __SOL_GPIO_H__

#include <STC8G.H>

#include <stdint.h>

void gpio_initialize(void);

typedef enum _gpio_mode_t
{
  GPIO_MODE_BID = 0, // 准双向口
  GPIO_MODE_PULL_PUSH_OUT = 1, // 推挽输出
  GPIO_MODE_IN = 2,  // 高阻输入
  GPIO_MODE_OD_OUT = 3,  // 开漏输出
} gpio_mode_t; 

void gpio_set_mode(uint8_t port, uint8_t bits, gpio_mode_t mode);

#define GPIO_PORT_P0 0x80
#define GPIO_PORT_P1 0x90
#define GPIO_PORT_P2 0xA0
#define GPIO_PORT_P3 0xB0
#define GPIO_PORT_P4 0xC0
#define GPIO_PORT_P5 0xC8

#define GPIO_SBIT(port, bit_offset) (port  ^ bit_offset)

/////////////////////////////////////////////////////
// 调试串口 USART1
#define GPIO_SERIAL_RXD_PORT GPIO_PORT_P3
#define GPIO_SERIAL_RXD_BIT  0
#define GPIO_SERIAL_TXD_PORT GPIO_PORT_P3
#define GPIO_SERIAL_TXD_BIT  1
sbit GPIO_SERIAL_RXD   = GPIO_SBIT(GPIO_SERIAL_RXD_PORT, GPIO_SERIAL_RXD_BIT);
sbit GPIO_SERIAL_TXD   = GPIO_SBIT(GPIO_SERIAL_TXD_PORT, GPIO_SERIAL_TXD_BIT);

// 蓝牙串口 USART2
#define GPIO_BT_RXD_PORT GPIO_PORT_P1
#define GPIO_BT_RXD_BIT  0
#define GPIO_BT_TXD_PORT GPIO_PORT_P1
#define GPIO_BT_TXD_BIT  1
#define GPIO_BT_EN_PORT GPIO_PORT_P5
#define GPIO_BT_EN_BIT  4
sbit GPIO_BT_RXD       = GPIO_SBIT(GPIO_BT_RXD_PORT, GPIO_BT_RXD_BIT);
sbit GPIO_BT_TXD       = GPIO_SBIT(GPIO_BT_TXD_PORT, GPIO_BT_TXD_BIT);
sbit GPIO_BT_EN        = GPIO_SBIT(GPIO_BT_EN_PORT, GPIO_BT_EN_BIT);
// i2c
#define GPIO_I2C_SDA_PORT GPIO_PORT_P1
#define GPIO_I2C_SDA_BIT  4
#define GPIO_I2C_SCL_PORT GPIO_PORT_P1
#define GPIO_I2C_SCL_BIT  5
sbit GPIO_I2C_SDA      = GPIO_SBIT(GPIO_I2C_SDA_PORT, GPIO_I2C_SDA_BIT);
sbit GPIO_I2C_SCL      = GPIO_SBIT(GPIO_I2C_SCL_PORT, GPIO_I2C_SCL_BIT);

// Power Manager
#define GPIO_POWER_EN_PORT    GPIO_PORT_P3
#define GPIO_POWER_EN_BIT     4
#define GPIO_POWER_CHRG_PORT  GPIO_PORT_P1
#define GPIO_POWER_CHRG_BIT   3
#define GPIO_POWER_STDBY_PORT GPIO_PORT_P3
#define GPIO_POWER_STDBY_BIT  6
#define GPIO_POWER_SOL_PORT   GPIO_PORT_P3
#define GPIO_POWER_SOL_BIT    7
#define GPIO_POWER_VOL_EN_PORT   GPIO_PORT_P5
#define GPIO_POWER_VOL_EN_BIT    5
#define GPIO_POWER_VOL_PORT   GPIO_PORT_P1
#define GPIO_POWER_VOL_BIT    7              // ADC CH 7
sbit GPIO_POWER_EN       = GPIO_SBIT(GPIO_POWER_EN_PORT, GPIO_POWER_EN_BIT);
sbit GPIO_POWER_CHRG     = GPIO_SBIT(GPIO_POWER_CHRG_PORT, GPIO_POWER_CHRG_BIT);
sbit GPIO_POWER_STDBY    = GPIO_SBIT(GPIO_POWER_STDBY_PORT, GPIO_POWER_STDBY_BIT);
sbit GPIO_POWER_SOL      = GPIO_SBIT(GPIO_POWER_SOL_PORT, GPIO_POWER_SOL_BIT);
sbit GPIO_POWER_VOL_EN   = GPIO_SBIT(GPIO_POWER_VOL_EN_PORT, GPIO_POWER_VOL_EN_BIT);
sbit GPIO_POWER_VOL      = GPIO_SBIT(GPIO_POWER_VOL_PORT, GPIO_POWER_VOL_BIT);

// Button
#define GPIO_KEY_INT_PORT    GPIO_PORT_P3
#define GPIO_KEY_INT_BIT     2
sbit GPIO_KEY_INT         = GPIO_SBIT(GPIO_KEY_INT_PORT, GPIO_KEY_INT_BIT);

// LW
#define GPIO_LW_INT_PORT    GPIO_PORT_P3
#define GPIO_LW_INT_BIT     3
sbit GPIO_LW_INT         = GPIO_SBIT(GPIO_LW_INT_PORT, GPIO_LW_INT_BIT);

// Moisture Sensor
#define GPIO_MOI_SENSOR_ADC_PORT    GPIO_PORT_P1
#define GPIO_MOI_SENSOR_ADC_BIT     2            
#define GPIO_MOI_PWM_PORT           GPIO_PORT_P3
#define GPIO_MOI_PWM_BIT            5
sbit GPIO_MOI_SENSOR_ADC = GPIO_SBIT(GPIO_MOI_SENSOR_ADC_PORT, GPIO_MOI_SENSOR_ADC_BIT); // ADC2
sbit GPIO_MOI_PWM        = GPIO_SBIT(GPIO_MOI_PWM_PORT, GPIO_MOI_PWM_BIT);  // CCP0

// OLED
#define GPIO_OLED_EN_PORT            GPIO_PORT_P1
#define GPIO_OLED_EN_BIT             6
sbit GPIO_OLED_EN        = GPIO_SBIT(GPIO_OLED_EN_PORT, GPIO_OLED_EN_BIT);

#endif // __SOL_GPIO_H__